import type { Optional } from '../utils/optional';

export interface FileAnalysis {
  path: string;
  hash: string;
  extractedFunctions: ExtractedFunction[];
  /* Import identifiers unrelated to extracted functions.
   * These are often generated by transforms such as
   * `import { mount } from '@testronaut/angular/browser`; */
  importedIdentifiers: ImportedIdentifier[];
  /* Names generated by transforms for runInBrowser calls.
   * These are excluded from duplicate checking since transforms
   * own the naming contract and can reuse names for identical functions. */
  generatedNames: Set<string>;
}

export function createFileAnalysis(
  fileAnalysis: Optional<FileAnalysis, 'extractedFunctions'>
): FileAnalysis {
  return {
    extractedFunctions: [],
    ...fileAnalysis,
  };
}

interface BaseExtractedFunction {
  importedIdentifiers: ImportedIdentifier[];
  code: string;
}

interface AnonymousExtractedFunction extends BaseExtractedFunction {
  type: 'anonymous';
  hash: string;
}

interface NamedExtractedFunction extends BaseExtractedFunction {
  type: 'named';
  name: string;
}

export function isAnonymousExtractedFunction(
  extractedFunction: ExtractedFunction
): extractedFunction is AnonymousExtractedFunction {
  return extractedFunction.type === 'anonymous';
}

export function isNamedExtractedFunction(
  extractedFunction: ExtractedFunction
): extractedFunction is NamedExtractedFunction {
  return extractedFunction.type === 'named';
}

export type ExtractedFunction =
  | AnonymousExtractedFunction
  | NamedExtractedFunction;

export const extractedFunctionsKey = 'extractedFunctionsRecord';

export type ExtractedFunctionsRecord = Record<
  'anonymous' | 'named',
  Record<string, string>
>;

export interface ExtractedFunctionsType {
  [extractedFunctionsKey]: ExtractedFunctionsRecord;
}

export interface ImportedIdentifier {
  name: string;
  module: string;
}

export function createAnonymousExtractedFunction(
  extractedFunction: Optional<
    AnonymousExtractedFunction,
    'importedIdentifiers' | 'type'
  >
): ExtractedFunction {
  return {
    type: 'anonymous',
    importedIdentifiers: [],
    ...extractedFunction,
  };
}

export function createNamedExtractedFunction(
  extractedFunction: Optional<
    NamedExtractedFunction,
    'importedIdentifiers' | 'type'
  >
): ExtractedFunction {
  return {
    type: 'named',
    importedIdentifiers: [],
    ...extractedFunction,
  };
}

export function createImportedIdentifier(
  importedIdentifier: ImportedIdentifier
): ImportedIdentifier {
  return importedIdentifier;
}
